### ISSUE TITLE
Add Femto metadata

### ISSUE THREAD

**Issue by alfonsogarciacaro** [alfonsogarciacaro/Elmish.Lit#1]

**Comment by AngelMunoz** [comment]
if we're just using the rendering side of lit I think this package would be ideal for femto metadata
https://lit.dev/docs/libraries/standalone-templates/

**Comment by alfonsogarciacaro** [comment]
Done! Although I couldn't install a prerelease package with Femto :/ https://github.com/Zaid-Ajaj/Femto/issues/76
